In [99]:
#----------------------------------
# Importar bibliotecas necessárias
#----------------------------------
import re
import pandas as pd
from pathlib import Path

#----------------------------------
# DIRETORIO
#----------------------------------
base_dir = "C:/Users/gabri/OneDrive/Área de Trabalho/joao/TB/cesta-de-precos-pncp"

#----------------------------------
# INPUTS
#----------------------------------
DATASET_ITEM_HOMOLOGADO = "tasks/verifica-descontos/inputs/item_homologado.csv"
DATASET_CONTRATACOES = "tasks/verifica-descontos/inputs/contratacao.csv"
LEGADOS_ITEM_HOMOLOGADO = "tasks/verifica-descontos/docs/outputs-dados-legados/medicamentos-legados.csv"
LEGADOS_CONTRATACOES = "tasks/verifica-descontos/docs/outputs-dados-legados/contratacoes-legados.csv"

#----------------------------------
# OUTPUTS
#----------------------------------


#----------------------------------
# Carrega o dataset de compras
#----------------------------------
DF_ITEM_HOMOLOGADO = pd.read_csv(f"{base_dir}/{DATASET_ITEM_HOMOLOGADO}")
DF_CONTRATACOES = pd.read_csv(f"{base_dir}/{DATASET_CONTRATACOES}")
DF_LEGADOS_ITEM_HOMOLOGADO = pd.read_csv(f"{base_dir}/{LEGADOS_ITEM_HOMOLOGADO}")
DF_LEGADOS_CONTRATACOES = pd.read_csv(f"{base_dir}/{LEGADOS_CONTRATACOES}")

C:\Users\gabri\AppData\Local\Temp\ipykernel_15244\3213193178.py:29: DtypeWarning: Columns (0: ni_fornecedor, 1: nome_catalogo, 2: nome_categoria_item_catalogo, 3: codigo_item_catalogo_pncp, 4: descricao_ncm_nbs, 5: data_cancelamento, 6: motivo_cancelamento) have mixed types. Specify dtype option on import or set low_memory=False.
  DF_ITEM_HOMOLOGADO = pd.read_csv(f"{base_dir}/{DATASET_ITEM_HOMOLOGADO}")
C:\Users\gabri\AppData\Local\Temp\ipykernel_15244\3213193178.py:31: DtypeWarning: Columns (0: tipoMargemPreferencia.nome, 1: tipoMargemPreferencia, 2: exigenciaConteudoNacional) have mixed types. Specify dtype option on import or set low_memory=False.
  DF_LEGADOS_ITEM_HOMOLOGADO = pd.read_csv(f"{base_dir}/{LEGADOS_ITEM_HOMOLOGADO}")

## Inspeciona dataset `DATASET_ITEM_HOMOLOGADO` e filtra colunas necessarias para análise

In [100]:
DF_ITEM_HOMOLOGADO.head()

,numero_controle_pncp,codigo_item_catalogo,cnpj_contratante,codigo_unidade_contratante,cnpj_contratante_subrogado,codigo_unidade_contratante_subrogado,ni_fornecedor,numero_item,descricao,unidade_medida,...,valor_total_homologado,quantidade_homologada,moeda_estrangeira,valor_nominal_moeda_estrangeira,data_resultado,data_cancelamento,motivo_cancelamento,url_api,url_pncp,data_insercao
0,92324706000127-1-000279/2023,302442,92324706000127,0000,NaN,NaN,8822673000139,5,Duloxetina 30mg.,COMPRIMIDO,...,316.80,180,NaN,NaN,2023-06-02T00:00:00Z,NaN,NaN,https://pncp.gov.br/api/pncp/v1/orgaos/9232470...,https://pncp.gov.br/app/editais/92324706000127...,2025-04-01T21:52:28Z
1,92324706000127-1-000279/2023,273422,92324706000127,0000,NaN,NaN,88212113029183,6,LOXOPROFENO SODICO 60mg COMPRIMIDOS,COMPRIMIDO,...,644.40,360,NaN,NaN,2023-06-02T00:00:00Z,NaN,NaN,https://pncp.gov.br/api/pncp/v1/orgaos/9232470...,https://pncp.gov.br/app/editais/92324706000127...,2025-04-01T21:52:28Z
2,92324706000127-1-000279/2023,436769,92324706000127,0000,NaN,NaN,15068089000103,7,VORTIOXETINA BROMID 10mg,UNIDADE,...,2131.20,360,NaN,NaN,2023-06-02T00:00:00Z,NaN,NaN,https://pncp.gov.br/api/pncp/v1/orgaos/9232470...,https://pncp.gov.br/app/editais/92324706000127...,2025-04-01T21:52:29Z
3,92324706000127-1-000279/2023,271848,92324706000127,0000,NaN,NaN,15068089000103,9,Bimatoprosta 0 3 mg ml,FRASCO,...,251.28,6,NaN,NaN,2023-06-02T00:00:00Z,NaN,NaN,https://pncp.gov.br/api/pncp/v1/orgaos/9232470...,https://pncp.gov.br/app/editais/92324706000127...,2025-04-01T21:52:29Z
4,92324706000127-1-000279/2023,267077,92324706000127,0000,NaN,NaN,88212113029183,10,Bezafibrato 200 mg,COMPRIMIDO,...,212.40,180,NaN,NaN,2023-06-02T00:00:00Z,NaN,NaN,https://pncp.gov.br/api/pncp/v1/orgaos/9232470...,https://pncp.gov.br/app/editais/92324706000127...,2025-04-01T21:52:29Z

In [101]:
colunas = [
    "numero_controle_pncp",
    "numero_item",
]

DF_ITEM_HOMOLOGADO_COLUNAS = DF_ITEM_HOMOLOGADO[colunas].copy()
print(f"Este dataset contém {DF_ITEM_HOMOLOGADO.shape[0]} linhas")
DF_ITEM_HOMOLOGADO_COLUNAS.head()

Este dataset contém 200205 linhas

           numero_controle_pncp  numero_item
0  92324706000127-1-000279/2023            5
1  92324706000127-1-000279/2023            6
2  92324706000127-1-000279/2023            7
3  92324706000127-1-000279/2023            9
4  92324706000127-1-000279/2023           10

## Inspeciona dataset `DF_LEGADOS_ITEM_HOMOLOGADO`

In [102]:
print(f"Este dataset contém {DF_LEGADOS_ITEM_HOMOLOGADO.shape[0]} linhas")
DF_LEGADOS_ITEM_HOMOLOGADO.rename(columns={"data.numeroControlePNCP": "numero_controle_pncp", "numeroItem": "numero_item"}, inplace=True)
DF_LEGADOS_ITEM_HOMOLOGADO.head()

Este dataset contém 316661 linhas

,numero_controle_pncp,numero_item,tipoBeneficioNome,aplicabilidadeMargemPreferenciaNormal,percentualMargemPreferenciaNormal,aplicabilidadeMargemPreferenciaAdicional,percentualMargemPreferenciaAdicional,tipoMargemPreferencia.codigo,criterioJulgamentoNome,tipoMargemPreferencia.nome,tipoMargemPreferencia,exigenciaConteudoNacional
0,88000906000157-1-000376/2024,1,Sem benefício,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN
1,88000906000157-1-000376/2024,2,Sem benefício,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN
2,88000906000157-1-000376/2024,3,Participação exclusiva para ME/EPP,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN
3,88000906000157-1-000376/2024,4,Participação exclusiva para ME/EPP,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN
4,88000906000157-1-000376/2024,5,Participação exclusiva para ME/EPP,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN

## Inspeciona dataset `DF_CONTRATACOES` e filtra colunas necessarias

In [103]:
DF_CONTRATACOES.head()

,numero_controle_pncp,ano_compra,sequencial_compra,objeto_compra,data_abertura_proposta,data_encerramento_proposta,valor_estimado_compra,valor_homologado_compra,srp,codigo_tipo_instrumento_convocatorio,nome_tipo_instrumento_convocatorio,codigo_modalidade,nome_modalidade,codigo_amparo_legal,nome_amparo_legal,codigo_modo_disputa,nome_modo_disputa,data_insercao,compra_judicial
0,12998458000160-1-000326/2024,2024,326,RC 2159/2024 A CONTRATACAO VISA ATENDER A NECE...,NaN,NaN,0.00,36.00,False,3,Ato que autoriza a Contratação Direta,8,Dispensa,19,"Lei 14.133/2021, Art. 75, II",5,Não se aplica,2025-04-01T18:40:28Z,False
1,44847663000111-1-000895/2025,2025,895,REGISTRO DE PREÇOS PARA AQUISIÇÃO DE MEDICAMEN...,2025-11-18T08:00:00Z,2025-12-02T08:59:00Z,108444.20,82440.44,True,1,Edital,6,Pregão - Eletrônico,1,"Lei 14.133/2021, Art. 28, I",1,Aberto,2026-02-25T20:57:44Z,False
2,48031918000124-1-001362/2024,2024,1362,Aquisição de insumos farmacológicos para o car...,NaN,NaN,1160.51,852.35,False,3,Ato que autoriza a Contratação Direta,8,Dispensa,20,"Lei 14.133/2021, Art. 75, III, a",5,Não se aplica,2025-04-01T18:40:28Z,False
3,12998458000160-1-000268/2024,2024,268,RC 653/2024 ATENDIMENTO DA REDE PUBLICA DE SAU...,NaN,NaN,0.00,7560.00,False,3,Ato que autoriza a Contratação Direta,8,Dispensa,19,"Lei 14.133/2021, Art. 75, II",5,Não se aplica,2025-04-01T18:40:28Z,False
4,12998458000160-1-000263/2024,2024,263,RC 1254/2024 ATENDIMENTO DA REDE PUBLICA DE SA...,NaN,NaN,0.00,360.00,False,3,Ato que autoriza a Contratação Direta,8,Dispensa,19,"Lei 14.133/2021, Art. 75, II",5,Não se aplica,2025-04-01T18:40:29Z,False

In [104]:
colunas = [
    "numero_controle_pncp",
    "srp",
]

DF_CONTRATACOES_COLUNAS = DF_CONTRATACOES[colunas].copy()
print(f"Este dataset contém {DF_CONTRATACOES.shape[0]} linhas")
DF_CONTRATACOES_COLUNAS.head()

Este dataset contém 101387 linhas

           numero_controle_pncp    srp
0  12998458000160-1-000326/2024  False
1  44847663000111-1-000895/2025   True
2  48031918000124-1-001362/2024  False
3  12998458000160-1-000268/2024  False
4  12998458000160-1-000263/2024  False

## Inspeciona dataset `DF_LEGADOS_CONTRATACOES`

In [105]:
print(f"Este dataset contém {DF_LEGADOS_CONTRATACOES.shape[0]} linhas")
DF_LEGADOS_CONTRATACOES.rename(columns={"data.numeroControlePNCP": "numero_controle_pncp"}, inplace=True)
DF_LEGADOS_CONTRATACOES.head()

Este dataset contém 79510 linhas

           numero_controle_pncp  data.srp
0  88000906000157-1-000376/2024      True
1  16726028000140-1-000043/2024      True
2  14814139000183-1-000207/2024      True
3  01409580000138-1-001988/2024      True
4  45787678000102-1-000494/2024      True

## Unir `DF_CONTRATACOES_COLUNAS` e `DF_ITEM_HOMOLOGADO_COLUNAS` com seus respectivos dados legados vindos do script `tasks\verifica-descontos\docs\analisa-descontos-dados-legados.ipynb`, de forma que os datasets atuais do banco recebam as colunas necessárias para as informações de desontos

### `DF_ITEM_HOMOLOGADO_COLUNAS`

In [106]:
# A correspondência entre os datasets é feita no nível do item.
chaves_item = ["numero_controle_pncp", "numero_item"]
colunas_legado = [
    coluna
    for coluna in DF_LEGADOS_ITEM_HOMOLOGADO.columns
    if coluna not in chaves_item
]

# Algumas chaves se repetem no legado. Um valor único permanece escalar; valores
# diferentes são preservados em lista para evitar perda de informação.
def preservar_valores_unicos(serie):
    valores = serie.dropna().unique().tolist()
    if not valores:
        return pd.NA
    return valores[0] if len(valores) == 1 else valores


chaves_repetidas = DF_LEGADOS_ITEM_HOMOLOGADO.duplicated(
    subset=chaves_item, keep=False
)
legados_sem_repeticao = DF_LEGADOS_ITEM_HOMOLOGADO.loc[~chaves_repetidas]
legados_repetidos_agrupados = (
    DF_LEGADOS_ITEM_HOMOLOGADO.loc[chaves_repetidas]
    .groupby(chaves_item, as_index=False, dropna=False)[colunas_legado]
    .agg(preservar_valores_unicos)
)
# Reúne verticalmente as linhas que já eram únicas e as repetições consolidadas.
DF_LEGADOS_ITEM_HOMOLOGADO_AGRUPADO = pd.concat(
    # Estes dois DataFrames têm as mesmas colunas e serão empilhados.
    [legados_sem_repeticao, legados_repetidos_agrupados],
    # Recria o índice para que ele seja contínuo após a concatenação.
    ignore_index=True
)

# Enriquece os itens atuais com as colunas do legado já consolidado.
DF_ITEM_HOMOLOGADO_COM_LEGADOS = DF_ITEM_HOMOLOGADO_COLUNAS.merge(
    DF_LEGADOS_ITEM_HOMOLOGADO_AGRUPADO, # DataFrame da direita, com no máximo uma linha por chave de item.
    on=chaves_item,  # Faz a correspondência pela contratação e pelo número do item.
    how="left", # Preserva todas as linhas do dataset atual, mesmo sem correspondência.
    suffixes=("", "_legado"), # Mantém nomes atuais e acrescenta '_legado' somente em colunas repetidas.
    indicator=True,  # Cria '_merge' para indicar 'both', 'left_only' ou 'right_only'.
    validate="many_to_one" # Garante várias linhas à esquerda e no máximo uma por chave à direita.
)

assert len(DF_ITEM_HOMOLOGADO_COM_LEGADOS) == len(DF_ITEM_HOMOLOGADO_COLUNAS), (
    "A junção alterou a quantidade de linhas de DF_ITEM_HOMOLOGADO_COLUNAS"
)

print(f"O dataset após o merge contém {DF_ITEM_HOMOLOGADO_COM_LEGADOS.shape[0]} linhas")

print(f"O dataset atual do BANCO DE DADOS contém {DF_ITEM_HOMOLOGADO_COLUNAS.shape[0]} linhas")
print(f"Diferença de {DF_ITEM_HOMOLOGADO_COM_LEGADOS.shape[0] - DF_ITEM_HOMOLOGADO_COLUNAS.shape[0]} linhas")
DF_ITEM_HOMOLOGADO_COM_LEGADOS.head()

O dataset após o merge contém 200205 linhas
O dataset atual do BANCO DE DADOS contém 200205 linhas
Diferença de 0 linhas

,numero_controle_pncp,numero_item,tipoBeneficioNome,aplicabilidadeMargemPreferenciaNormal,percentualMargemPreferenciaNormal,aplicabilidadeMargemPreferenciaAdicional,percentualMargemPreferenciaAdicional,tipoMargemPreferencia.codigo,criterioJulgamentoNome,tipoMargemPreferencia.nome,tipoMargemPreferencia,exigenciaConteudoNacional,_merge
0,92324706000127-1-000279/2023,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,92324706000127-1-000279/2023,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,92324706000127-1-000279/2023,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,92324706000127-1-000279/2023,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,92324706000127-1-000279/2023,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [107]:
# Linhas que receberam informações do legado
linhas_com_legado = DF_ITEM_HOMOLOGADO_COM_LEGADOS.query('_merge == "both"')

print(f"O dataset após merge contém {DF_ITEM_HOMOLOGADO_COM_LEGADOS.shape[0]} linhas")
print(f"Linhas com informações do legado: {linhas_com_legado.shape[0]}")
linhas_com_legado.head()

O dataset após merge contém 200205 linhas
Linhas com informações do legado: 138921

,numero_controle_pncp,numero_item,tipoBeneficioNome,aplicabilidadeMargemPreferenciaNormal,percentualMargemPreferenciaNormal,aplicabilidadeMargemPreferenciaAdicional,percentualMargemPreferenciaAdicional,tipoMargemPreferencia.codigo,criterioJulgamentoNome,tipoMargemPreferencia.nome,tipoMargemPreferencia,exigenciaConteudoNacional,_merge
13,15126437000143-1-002819/2023,4,Não se aplica,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN,both
14,15126437000143-1-002819/2023,5,Não se aplica,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN,both
15,15126437000143-1-002819/2023,6,Não se aplica,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN,both
16,15126437000143-1-002819/2023,3,Não se aplica,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN,both
18,15126437000143-1-001737/2023,2,Não se aplica,False,NaN,False,NaN,NaN,Menor preço,NaN,NaN,NaN,both

In [108]:
# Linhas que não receberam informações do legado
linhas_sem_legado = DF_ITEM_HOMOLOGADO_COM_LEGADOS.query('_merge == "left_only"')

print(f"Linhas que não tiveram correspondência no legado: {linhas_sem_legado.shape[0]}")
linhas_sem_legado.head()

Linhas que não tiveram correspondência no legado: 61284

,numero_controle_pncp,numero_item,tipoBeneficioNome,aplicabilidadeMargemPreferenciaNormal,percentualMargemPreferenciaNormal,aplicabilidadeMargemPreferenciaAdicional,percentualMargemPreferenciaAdicional,tipoMargemPreferencia.codigo,criterioJulgamentoNome,tipoMargemPreferencia.nome,tipoMargemPreferencia,exigenciaConteudoNacional,_merge
0,92324706000127-1-000279/2023,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,92324706000127-1-000279/2023,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,92324706000127-1-000279/2023,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,92324706000127-1-000279/2023,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,92324706000127-1-000279/2023,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

#### Dados e métricas pós análise:

In [109]:
total = len(DF_ITEM_HOMOLOGADO_COM_LEGADOS)

print(f"Total de linhas atuais: {total}")
print(f"Linhas impactadas por dados legados: {linhas_com_legado.shape[0]}")
print(f"Linhas sem dados legados: {linhas_sem_legado.shape[0]}")
print(f"Cobertura: {linhas_com_legado.shape[0] / total:.2%}")

Total de linhas atuais: 200205
Linhas impactadas por dados legados: 138921
Linhas sem dados legados: 61284
Cobertura: 69.39%

### `DF_CONTRATACOES_COLUNAS`

In [110]:
chave_contratacao = ["numero_controle_pncp"]
colunas_legado_contratacoes = [
    coluna
    for coluna in DF_LEGADOS_CONTRATACOES.columns
    if coluna not in chave_contratacao
]

chaves_contratacoes_repetidas = DF_LEGADOS_CONTRATACOES.duplicated(
    subset=chave_contratacao, keep=False
)
contratacoes_legadas_sem_repeticao = DF_LEGADOS_CONTRATACOES.loc[
    ~chaves_contratacoes_repetidas
]
contratacoes_legadas_repetidas_agrupadas = (
    DF_LEGADOS_CONTRATACOES.loc[chaves_contratacoes_repetidas]
    .groupby(
        chave_contratacao, as_index=False, dropna=False
    )[colunas_legado_contratacoes]
    .agg(preservar_valores_unicos)
)
# Reúne verticalmente as contratações únicas e as repetições consolidadas.
DF_LEGADOS_CONTRATACOES_AGRUPADO = pd.concat(
    # Os DataFrames da lista serão empilhados, preservando as mesmas colunas.
    [
        # Contratações que já possuíam uma única linha no legado.
        contratacoes_legadas_sem_repeticao,
        # Contratações repetidas após a preservação dos valores únicos.
        contratacoes_legadas_repetidas_agrupadas,
    ],
    # Descarta os índices anteriores e cria um índice contínuo.
    ignore_index=True
)

# Enriquece as contratações atuais com as colunas do legado consolidado.
DF_CONTRATACOES_COM_LEGADOS = DF_CONTRATACOES_COLUNAS.merge(
    # DataFrame da direita, com uma única linha para cada contratação.
    DF_LEGADOS_CONTRATACOES_AGRUPADO,
    # Relaciona os datasets pelo identificador único da contratação no PNCP.
    on=chave_contratacao,
    # Preserva todas as contratações atuais, mesmo sem dados legados.
    how="left",
    # Mantém nomes atuais e acrescenta '_legado' em eventuais colisões.
    suffixes=("", "_legado"),
    # Cria '_merge' para permitir a auditoria das correspondências.
    indicator=True,
    # Confirma que existe no máximo uma linha por chave em cada lado.
    validate="one_to_one"
)

assert len(DF_CONTRATACOES_COM_LEGADOS) == len(DF_CONTRATACOES_COLUNAS), (
    "A junção alterou a quantidade de linhas de DF_CONTRATACOES_COLUNAS"
)

print(f"O dataset após o merge contém {DF_CONTRATACOES_COM_LEGADOS.shape[0]} linhas")
print(f"O dataset atual do BANCO DE DADOS contém {DF_CONTRATACOES_COLUNAS.shape[0]} linhas")
print(f"Diferença de {DF_CONTRATACOES_COM_LEGADOS.shape[0] - DF_CONTRATACOES_COLUNAS.shape[0]} linhas")
DF_CONTRATACOES_COM_LEGADOS.head()

O dataset após o merge contém 101387 linhas
O dataset atual do BANCO DE DADOS contém 101387 linhas
Diferença de 0 linhas

           numero_controle_pncp    srp data.srp     _merge
0  12998458000160-1-000326/2024  False      NaN  left_only
1  44847663000111-1-000895/2025   True     True       both
2  48031918000124-1-001362/2024  False      NaN  left_only
3  12998458000160-1-000268/2024  False      NaN  left_only
4  12998458000160-1-000263/2024  False      NaN  left_only

In [111]:
# Linhas que receberam informações do legado
linhas_contratacoes_com_legado = DF_CONTRATACOES_COM_LEGADOS.query('_merge == "both"')

print(f"Linhas com informações do legado: {linhas_contratacoes_com_legado.shape[0]}")
linhas_contratacoes_com_legado.head()

Linhas com informações do legado: 62258

            numero_controle_pncp    srp data.srp _merge
1   44847663000111-1-000895/2025   True     True   both
12  87862397000109-1-000514/2025  False    False   both
13  48031918000124-1-001078/2024   True     True   both
18  00394429000100-1-000644/2023   True     True   both
19  00394429000100-1-001883/2023   True     True   both

In [112]:
# Linhas que não receberam informações do legado
linhas_contratacoes_sem_legado = DF_CONTRATACOES_COM_LEGADOS.query('_merge == "left_only"')

print(f"Linhas que não tiveram correspondência no legado: {linhas_contratacoes_sem_legado.shape[0]}")
linhas_contratacoes_sem_legado.head()

Linhas que não tiveram correspondência no legado: 39129

           numero_controle_pncp    srp data.srp     _merge
0  12998458000160-1-000326/2024  False      NaN  left_only
2  48031918000124-1-001362/2024  False      NaN  left_only
3  12998458000160-1-000268/2024  False      NaN  left_only
4  12998458000160-1-000263/2024  False      NaN  left_only
5  12998458000160-1-000250/2024  False      NaN  left_only

#### Dados e métricas pós análise:

In [113]:
total_contratacoes = len(DF_CONTRATACOES_COM_LEGADOS)
impactadas_contratacoes = linhas_contratacoes_com_legado.shape[0]
sem_legado_contratacoes = linhas_contratacoes_sem_legado.shape[0]

print(f"Total de linhas atuais: {total_contratacoes}")
print(f"Linhas impactadas por dados legados: {impactadas_contratacoes}")
print(f"Linhas sem dados legados: {sem_legado_contratacoes}")
print(f"Cobertura: {impactadas_contratacoes / total_contratacoes:.2%}")

Total de linhas atuais: 101387
Linhas impactadas por dados legados: 62258
Linhas sem dados legados: 39129
Cobertura: 61.41%

## Integrar `srp` das contratações aos itens homologados

A coluna `srp` é associada aos itens por `numero_controle_pncp`. A junção é do tipo `left`, portanto mantém todas as linhas de `DF_ITEM_HOMOLOGADO_COM_LEGADOS` e preenche `srp` apenas quando a contratação correspondente existe.

In [114]:
quantidade_itens_antes_srp = len(DF_ITEM_HOMOLOGADO_COM_LEGADOS)

# Seleciona somente a chave da contratação e a coluna que será levada aos itens.
# Cria uma cópia independente para evitar alterações acidentais no DataFrame original.
DF_SRP_POR_CONTRATACAO = DF_CONTRATACOES_COM_LEGADOS[
    ["numero_controle_pncp", "srp"]
].copy()

# Associa o indicador de SRP de cada contratação aos seus respectivos itens.
DF_ITEM_HOMOLOGADO_COM_LEGADOS_E_SRP = DF_ITEM_HOMOLOGADO_COM_LEGADOS.merge(
    DF_SRP_POR_CONTRATACAO, # DataFrame da direita, contendo uma linha por contratação e seu valor de srp
    on="numero_controle_pncp", # Repete o valor de srp nos itens que possuem o mesmo número de controle PNCP.
    how="left", # Mantém todos os itens, inclusive quando a contratação não for encontrada.
    validate="many_to_one", # Valida que vários itens podem apontar para somente uma contratação.
    indicator="_merge_srp" # Cria uma coluna específica para auditar a correspondência desta junção.
)

assert len(DF_ITEM_HOMOLOGADO_COM_LEGADOS_E_SRP) == quantidade_itens_antes_srp, (
    "A integração de srp alterou a quantidade de itens homologados"
)

itens_com_srp = DF_ITEM_HOMOLOGADO_COM_LEGADOS_E_SRP["_merge_srp"].eq("both").sum()
itens_sem_contratacao = (
    DF_ITEM_HOMOLOGADO_COM_LEGADOS_E_SRP["_merge_srp"].eq("left_only").sum()
)

print(f"Itens antes da integração de srp: {quantidade_itens_antes_srp}")
print(f"Itens após a integração de srp: {len(DF_ITEM_HOMOLOGADO_COM_LEGADOS_E_SRP)}")
print(f"Itens associados a uma contratação: {itens_com_srp}")
print(f"Itens sem contratação correspondente: {itens_sem_contratacao}")
DF_ITEM_HOMOLOGADO_COM_LEGADOS_E_SRP.head()

Itens antes da integração de srp: 200205
Itens após a integração de srp: 200205
Itens associados a uma contratação: 200205
Itens sem contratação correspondente: 0

,numero_controle_pncp,numero_item,tipoBeneficioNome,aplicabilidadeMargemPreferenciaNormal,percentualMargemPreferenciaNormal,aplicabilidadeMargemPreferenciaAdicional,percentualMargemPreferenciaAdicional,tipoMargemPreferencia.codigo,criterioJulgamentoNome,tipoMargemPreferencia.nome,tipoMargemPreferencia,exigenciaConteudoNacional,_merge,srp,_merge_srp
0,92324706000127-1-000279/2023,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False,both
1,92324706000127-1-000279/2023,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False,both
2,92324706000127-1-000279/2023,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False,both
3,92324706000127-1-000279/2023,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False,both
4,92324706000127-1-000279/2023,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False,both